from __future__ import annotations

from urllib.parse import urlsplit


def build_production_htaccess(site_url: str) -> str:
    """Build the default Apache/LiteSpeed .htaccess used by clean rebuilds.

    The template is intentionally generated from known-safe defaults instead of
    restoring the compromised site's old .htaccess. HTTPS redirect is enabled
    only when site_url itself uses https. WordPress rewrite targets are derived
    from the URL path so subdirectory installs keep working.
    """
    parsed = urlsplit(site_url)
    path = parsed.path.rstrip("/")
    rewrite_base = f"{path}/" if path else "/"
    index_target = f"{path}/index.php" if path else "/index.php"

    lines = [
        "# =============================================================",
        "# LiteSpeed/Apache + WordPress — Minimal, Fast, Secure",
        "# Generated by WP Clean Rebuild; do not restore compromised rules verbatim.",
        "# =============================================================",
        "",
        "# 0) Force HTTPS (giữ nguyên www/non-www hiện tại)",
    ]

    if parsed.scheme.lower() == "https":
        lines.extend(
            [
                "RewriteEngine On",
                "RewriteCond %{HTTPS} !=on",
                "RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]",
            ]
        )
    else:
        lines.append("# HTTPS redirect disabled because siteUrl is not https.")

    lines.extend(
        [
            "",
            "# Nếu muốn ép hướng www/non-www, mở 1 khối dưới và sửa đúng domain:",
            "# -- non-www -> www --",
            "#RewriteCond %{HTTP_HOST} !^www\\. [NC]",
            "#RewriteRule ^ https://www.%{HTTP_HOST}%{REQUEST_URI} [L,R=301]",
            "# -- www -> non-www --",
            "#RewriteCond %{HTTP_HOST} ^www\\.(.+)$ [NC]",
            "#RewriteRule ^ https://%1%{REQUEST_URI} [L,R=301]",
            "",
            "# 1) Security headers (an toàn, ít xung đột)",
            "<IfModule mod_headers.c>",
            '  Header always set X-Content-Type-Options "nosniff"',
            '  Header always set X-Frame-Options "SAMEORIGIN"',
            '  Header always set Referrer-Policy "strict-origin-when-cross-origin"',
            '  Header always set Permissions-Policy "camera=(), microphone=(), geolocation=()"',
            "  # BẬT KHI TOÀN BỘ (kể cả subdomain) đã HTTPS:",
            '  # Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"',
            "</IfModule>",
            "",
            "# 2) Hardening cơ bản",
            "Options -Indexes",
            "",
            "# Chặn file nhạy cảm",
            '<FilesMatch "^(wp-config\\.php|\\.env|composer\\.(json|lock))$">',
            "  Require all denied",
            "</FilesMatch>",
            "",
            "# Chặn xmlrpc nếu không dùng",
            "<Files xmlrpc.php>",
            "  Require all denied",
            "</Files>",
            "",
            "# 3) Static cache (browser cache) — nhẹ, hiệu quả",
            "<IfModule mod_expires.c>",
            "  ExpiresActive On",
            "  # CSS/JS",
            '  ExpiresByType text/css "access plus 30 days"',
            '  ExpiresByType application/javascript "access plus 30 days"',
            '  ExpiresByType text/javascript "access plus 30 days"',
            "  # Fonts",
            '  ExpiresByType font/woff2 "access plus 180 days"',
            '  ExpiresByType application/font-woff2 "access plus 180 days"',
            "  # Images",
            '  ExpiresByType image/avif "access plus 180 days"',
            '  ExpiresByType image/webp "access plus 180 days"',
            '  ExpiresByType image/png "access plus 30 days"',
            '  ExpiresByType image/jpeg "access plus 30 days"',
            '  ExpiresByType image/gif "access plus 30 days"',
            '  ExpiresByType image/svg+xml "access plus 30 days"',
            "  # Default",
            '  ExpiresDefault "access plus 7 days"',
            "</IfModule>",
            "",
            "<IfModule mod_headers.c>",
            "  # immutable cho file có đặt tên kèm hash (khuyến nghị khi build assets)",
            '  <FilesMatch "\\.(css|js|woff2|avif|webp)$">',
            '    Header set Cache-Control "public, max-age=2592000, immutable"',
            "  </FilesMatch>",
            '  <FilesMatch "\\.(png|jpe?g|gif|svg)$">',
            '    Header set Cache-Control "public, max-age=2592000"',
            "  </FilesMatch>",
            "</IfModule>",
            "",
            "# 4) MIME types",
            "AddType image/svg+xml .svg",
            "AddType image/avif .avif",
            "AddType image/webp .webp",
            "AddType application/font-woff2 .woff2",
            "",
            "# 5) CORS cho font (tránh lỗi khi dùng CDN/subdomain)",
            "<IfModule mod_headers.c>",
            '  <FilesMatch "\\.(woff2?|ttf|otf|eot)$">',
            '    Header set Access-Control-Allow-Origin "*"',
            "  </FilesMatch>",
            "</IfModule>",
            "",
            "# 6) SVG an toàn (ngăn thực thi script)",
            "<IfModule mod_headers.c>",
            '  <FilesMatch "\\.svg$">',
            '    Header set Content-Security-Policy "sandbox"',
            "  </FilesMatch>",
            "</IfModule>",
            "",
            "# 7) Ưu tiên AVIF/WebP nếu có file cùng tên (không cần plugin)",
            "#   /uploads/img.jpg -> sẽ serve img.avif nếu tồn tại và trình duyệt hỗ trợ",
            "RewriteCond %{REQUEST_FILENAME} (.*)\\.(jpe?g|png)$ [NC]",
            "RewriteCond %1.avif -f",
            'RewriteCond %{HTTP_ACCEPT} "image/avif"',
            "RewriteRule ^ %1.avif [L]",
            "",
            "RewriteCond %{REQUEST_FILENAME} (.*)\\.(jpe?g|png)$ [NC]",
            "RewriteCond %1.webp -f",
            'RewriteCond %{HTTP_ACCEPT} "image/webp"',
            "RewriteRule ^ %1.webp [L]",
            "",
            "# 8) (Tuỳ chọn) Chống hotlink ảnh — thay yourdomain.com nếu bật",
            "#RewriteCond %{HTTP_REFERER} !^$",
            "#RewriteCond %{HTTP_REFERER} !^https?://(www\\.)?yourdomain\\.com/ [NC]",
            "#RewriteRule \\.(jpe?g|png|gif|webp|avif)$ - [F,NC,L]",
            "",
            "# 9) Bật tra cứu cache của LiteSpeed (HTML cache thực thụ vẫn nên dùng plugin LiteSpeed Cache)",
            "<IfModule LiteSpeed>",
            "  CacheLookup on",
            "</IfModule>",
            "",
            "# =============================================================",
            "# 10) WordPress pretty permalinks (GIỮ Ở CUỐI)",
            "# =============================================================",
            "# BEGIN WordPress",
            '<IfModule mod_rewrite.c>',
            "RewriteEngine On",
            "RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]",
            f"RewriteBase {rewrite_base}",
            "RewriteRule ^index\\.php$ - [L]",
            "RewriteCond %{REQUEST_FILENAME} !-f",
            "RewriteCond %{REQUEST_FILENAME} !-d",
            f"RewriteRule . {index_target} [L]",
            "</IfModule>",
            "# END WordPress",
            "",
        ]
    )
    return "\n".join(lines)


__all__ = ["build_production_htaccess"]
