from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from ftplib import error_perm
from pathlib import Path, PurePosixPath
from tempfile import TemporaryDirectory
from typing import Callable
from urllib.request import Request, urlopen
import hashlib
import io
import json
import re
import secrets
import threading
import zipfile

from .backup import verify_manifest
from .site_config import SiteConnectionProfile
from .transport import FTPTransport


ProgressCallback = Callable[[dict], None]
WORDPRESS_LATEST_ZIP = "https://wordpress.org/latest.zip"
SALT_KEYS = (
    "AUTH_KEY",
    "SECURE_AUTH_KEY",
    "LOGGED_IN_KEY",
    "NONCE_KEY",
    "AUTH_SALT",
    "SECURE_AUTH_SALT",
    "LOGGED_IN_SALT",
    "NONCE_SALT",
)


@dataclass(slots=True)
class RebuildExecuteReport:
    host: str
    remote_root: str
    backup_root: str
    started_at: str
    finished_at: str | None = None
    original_backup_verified: bool = False
    clean_staging_verified: bool = False
    preflight_verified: bool = False
    wordpress_package_url: str = WORDPRESS_LATEST_ZIP
    wordpress_package_sha256: str = ""
    wordpress_version: str = ""
    wiped_files: int = 0
    wiped_dirs: int = 0
    preserved_paths: list[str] = field(default_factory=list)
    core_uploaded: int = 0
    uploads_uploaded: int = 0
    plugins_uploaded: int = 0
    themes_uploaded: int = 0
    mu_plugins_uploaded: int = 0
    wp_config_uploaded: bool = False
    database_imported: bool = False
    database_statements: int = 0
    temp_bridge_removed: bool = False
    temp_sql_removed: bool = False
    restore_backup_code: bool = False
    warnings: list[str] = field(default_factory=list)
    completed: bool = False


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _php_single_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def _read_define(source: str, name: str) -> str | None:
    pattern = re.compile(
        rf"define\s*\(\s*['\"]{re.escape(name)}['\"]\s*,\s*(['\"])(.*?)\1\s*\)\s*;",
        re.I | re.S,
    )
    match = pattern.search(source)
    return match.group(2) if match else None


def _database_credentials(config_path: Path) -> dict[str, str]:
    source = config_path.read_text(encoding="utf-8", errors="replace")
    values: dict[str, str] = {}
    for name in ("DB_NAME", "DB_USER", "DB_PASSWORD", "DB_HOST"):
        value = _read_define(source, name)
        if value is None:
            raise ValueError(f"Could not read {name} from backed-up wp-config.php.")
        values[name] = value
    values["DB_CHARSET"] = _read_define(source, "DB_CHARSET") or "utf8mb4"
    values["DB_COLLATE"] = _read_define(source, "DB_COLLATE") or ""
    return values


def _new_salt() -> str:
    return secrets.token_urlsafe(64)


def build_fresh_wp_config(config_path: Path, *, table_prefix: str) -> str:
    db = _database_credentials(config_path)
    lines = [
        "<?php",
        "/** Generated by WP Clean Rebuild. Do not restore the compromised wp-config.php verbatim. */",
        f"define('DB_NAME', '{_php_single_quote(db['DB_NAME'])}');",
        f"define('DB_USER', '{_php_single_quote(db['DB_USER'])}');",
        f"define('DB_PASSWORD', '{_php_single_quote(db['DB_PASSWORD'])}');",
        f"define('DB_HOST', '{_php_single_quote(db['DB_HOST'])}');",
        f"define('DB_CHARSET', '{_php_single_quote(db['DB_CHARSET'])}');",
        f"define('DB_COLLATE', '{_php_single_quote(db['DB_COLLATE'])}');",
        "",
    ]
    for key in SALT_KEYS:
        lines.append(f"define('{key}', '{_php_single_quote(_new_salt())}');")
    lines.extend(
        [
            "",
            f"$table_prefix = '{_php_single_quote(table_prefix)}';",
            "define('WP_DEBUG', false);",
            "define('DISALLOW_FILE_EDIT', true);",
            "",
            "if ( ! defined('ABSPATH') ) {",
            "    define('ABSPATH', __DIR__ . '/');",
            "}",
            "require_once ABSPATH . 'wp-settings.php';",
            "",
        ]
    )
    return "\n".join(lines)


def _download_wordpress_package(progress: ProgressCallback | None = None) -> bytes:
    if progress:
        progress({"phase": "download_core", "url": WORDPRESS_LATEST_ZIP})
    request = Request(
        WORDPRESS_LATEST_ZIP,
        headers={"User-Agent": "WP-Clean-Rebuild/0.4", "Accept": "application/zip"},
        method="GET",
    )
    with urlopen(request, timeout=180) as response:
        data = response.read()
    if len(data) < 1024 * 1024:
        raise RuntimeError("Downloaded WordPress package is unexpectedly small.")
    if not data.startswith(b"PK"):
        raise RuntimeError("Downloaded WordPress package is not a ZIP archive.")
    return data


def _extract_wordpress(data: bytes, destination: Path) -> str:
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        names = archive.namelist()
        required = "wordpress/wp-includes/version.php"
        if required not in names:
            raise RuntimeError("Official package layout check failed: wp-includes/version.php is missing.")
        for member in archive.infolist():
            name = member.filename
            if not name.startswith("wordpress/"):
                continue
            rel = PurePosixPath(name).relative_to("wordpress")
            if not rel.parts:
                continue
            target = destination.joinpath(*rel.parts)
            resolved = target.resolve()
            if destination.resolve() not in resolved.parents and resolved != destination.resolve():
                raise RuntimeError(f"Unsafe ZIP member path: {name}")
            if member.is_dir():
                target.mkdir(parents=True, exist_ok=True)
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            with archive.open(member) as src, target.open("wb") as dst:
                while chunk := src.read(1024 * 1024):
                    dst.write(chunk)

    version_php = (destination / "wp-includes" / "version.php").read_text(
        encoding="utf-8", errors="replace"
    )
    match = re.search(r"\$wp_version\s*=\s*['\"]([^'\"]+)['\"]", version_php)
    if not match:
        raise RuntimeError("Could not determine WordPress version from clean package.")
    return match.group(1)


def _wipe_remote_root(
    transport: FTPTransport,
    remote_root: str,
    *,
    progress: ProgressCallback | None = None,
) -> tuple[int, int, list[str]]:
    client = transport._new_client()
    deleted_files = 0
    deleted_dirs = 0
    preserved: list[str] = []
    lock = threading.Lock()

    def emit(current: str) -> None:
        if progress:
            progress(
                {
                    "phase": "wipe",
                    "deleted_files": deleted_files,
                    "deleted_dirs": deleted_dirs,
                    "current": current,
                }
            )

    def remove_dir(path: str, *, root: bool = False) -> None:
        nonlocal deleted_files, deleted_dirs
        entries = list(transport._mlsd(client, path))
        for name, facts in entries:
            if name in {".", ".."}:
                continue
            if root and name == ".well-known":
                preserved.append(str(PurePosixPath(path) / name))
                continue
            child = str(PurePosixPath(path) / name)
            kind = (facts.get("type") or "").lower()
            if kind in {"dir", "cdir", "pdir"}:
                if kind == "dir":
                    remove_dir(child)
                    client.rmd(child)
                    with lock:
                        deleted_dirs += 1
                    emit(child)
                continue
            client.delete(child)
            with lock:
                deleted_files += 1
            emit(child)

    try:
        remove_dir(remote_root, root=True)
        remaining = []
        for name, _facts in list(transport._mlsd(client, remote_root)):
            if name in {".", "..", ".well-known"}:
                continue
            remaining.append(name)
        if remaining:
            raise RuntimeError(
                "Remote wipe did not reach an empty WordPress root; remaining entries: "
                + ", ".join(remaining[:20])
            )
        return deleted_files, deleted_dirs, preserved
    finally:
        try:
            client.quit()
        except Exception:
            client.close()


def _ensure_remote_dir(client, remote_dir: str) -> None:
    path = PurePosixPath(remote_dir)
    if str(path) in {"", ".", "/"}:
        return
    try:
        client.cwd(str(path))
        return
    except Exception:
        pass

    current = "/" if str(path).startswith("/") else client.pwd()
    for part in path.parts:
        if part in {"", "/"}:
            continue
        current = str(PurePosixPath(current) / part)
        try:
            client.cwd(current)
        except error_perm:
            try:
                client.mkd(current)
            except error_perm:
                pass
            client.cwd(current)


def _upload_tree(
    transport: FTPTransport,
    local_root: Path,
    remote_root: str,
    *,
    progress_phase: str,
    progress: ProgressCallback | None = None,
) -> int:
    files = [p for p in local_root.rglob("*") if p.is_file()]
    if not files:
        return 0

    workers = max(1, min(transport.config.workers, len(files)))
    chunks = [files[index::workers] for index in range(workers)]
    completed = 0
    lock = threading.Lock()

    def worker(chunk: list[Path]) -> int:
        nonlocal completed
        client = transport._new_client()
        uploaded = 0
        try:
            for path in chunk:
                rel = path.relative_to(local_root)
                remote_path = str(PurePosixPath(remote_root).joinpath(*rel.parts))
                _ensure_remote_dir(client, str(PurePosixPath(remote_path).parent))
                with path.open("rb") as fh:
                    client.storbinary(
                        f"STOR {remote_path}",
                        fh,
                        blocksize=transport.config.block_size,
                    )
                uploaded += 1
                with lock:
                    completed += 1
                    current_completed = completed
                if progress:
                    progress(
                        {
                            "phase": progress_phase,
                            "files_completed": current_completed,
                            "files_total": len(files),
                            "current": remote_path,
                        }
                    )
            return uploaded
        finally:
            try:
                client.quit()
            except Exception:
                client.close()

    total = 0
    with ThreadPoolExecutor(max_workers=workers, thread_name_prefix="wpclean-upload") as pool:
        futures = [pool.submit(worker, chunk) for chunk in chunks if chunk]
        for future in as_completed(futures):
            total += future.result()
    return total


def _upload_text(transport: FTPTransport, remote_path: str, content: str) -> None:
    client = transport._new_client()
    try:
        _ensure_remote_dir(client, str(PurePosixPath(remote_path).parent))
        client.storbinary(
            f"STOR {remote_path}",
            io.BytesIO(content.encode("utf-8")),
            blocksize=transport.config.block_size,
        )
    finally:
        try:
            client.quit()
        except Exception:
            client.close()


def _upload_file(transport: FTPTransport, remote_path: str, local_path: Path) -> None:
    client = transport._new_client()
    try:
        _ensure_remote_dir(client, str(PurePosixPath(remote_path).parent))
        with local_path.open("rb") as fh:
            client.storbinary(
                f"STOR {remote_path}",
                fh,
                blocksize=transport.config.block_size,
            )
    finally:
        try:
            client.quit()
        except Exception:
            client.close()


def _delete_remote_file(transport: FTPTransport, remote_path: str) -> bool:
    client = transport._new_client()
    try:
        client.delete(remote_path)
        return True
    except Exception:
        return False
    finally:
        try:
            client.quit()
        except Exception:
            client.close()


def _database_import_bridge(token: str, data_name: str) -> str:
    return r'''<?php
@set_time_limit(0);
@ini_set('memory_limit', '256M');
@ini_set('display_errors', '0');
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');

const WPCLEAN_TOKEN = '__TOKEN__';
const WPCLEAN_DATA = '__DATA__';

function respond($ok, $message, $extra = array(), $status = 200) {
    http_response_code($status);
    echo json_encode(array_merge(array('ok' => $ok, 'message' => $message), $extra));
    exit;
}

$provided = isset($_SERVER['HTTP_X_WPCLEAN_TOKEN']) ? (string) $_SERVER['HTTP_X_WPCLEAN_TOKEN'] : '';
if ($provided === '' || !hash_equals(WPCLEAN_TOKEN, $provided)) {
    respond(false, 'unauthorized', array(), 403);
}

$configPath = __DIR__ . '/wp-config.php';
if (!is_file($configPath) || !is_readable($configPath)) {
    respond(false, 'wp-config.php not readable', array(), 500);
}
$config = file_get_contents($configPath);
if ($config === false) {
    respond(false, 'failed to read wp-config.php', array(), 500);
}

function read_define($source, $name) {
    $quoted = preg_quote($name, '/');
    $pattern = '/define\s*\(\s*[\'\"]' . $quoted . '[\'\"]\s*,\s*([\'\"])(.*?)\1\s*\)\s*;/s';
    if (!preg_match($pattern, $source, $matches)) {
        return null;
    }
    return stripcslashes($matches[2]);
}

$dbName = read_define($config, 'DB_NAME');
$dbUser = read_define($config, 'DB_USER');
$dbPass = read_define($config, 'DB_PASSWORD');
$dbHost = read_define($config, 'DB_HOST');
if ($dbName === null || $dbUser === null || $dbPass === null || $dbHost === null) {
    respond(false, 'unsupported wp-config database credential format', array(), 500);
}

$host = $dbHost;
$port = 3306;
$socket = null;
if (strpos($dbHost, ':') !== false) {
    if (preg_match('/^(.+):(\d+)$/', $dbHost, $m)) {
        $host = $m[1];
        $port = (int) $m[2];
    } elseif (preg_match('/^(.+):(.+\.sock)$/', $dbHost, $m)) {
        $host = $m[1];
        $socket = $m[2];
    }
}

mysqli_report(MYSQLI_REPORT_OFF);
$db = @new mysqli($host, $dbUser, $dbPass, $dbName, $port, $socket);
if ($db->connect_errno) {
    respond(false, 'database connection failed', array('errno' => $db->connect_errno), 500);
}
$db->set_charset('utf8mb4');

$dataPath = __DIR__ . '/' . WPCLEAN_DATA;
$fh = @fopen($dataPath, 'rb');
if (!$fh) {
    respond(false, 'temporary SQL data is not readable', array(), 500);
}

$statement = '';
$statements = 0;
while (($line = fgets($fh)) !== false) {
    $trim = ltrim($line);
    if ($statement === '' && ($trim === '' || substr($trim, 0, 2) === '--' || substr($trim, 0, 1) === '#')) {
        continue;
    }
    $statement .= $line;
    if (preg_match('/;\s*$/', $line)) {
        if (!$db->query($statement)) {
            $error = $db->error;
            $errno = $db->errno;
            fclose($fh);
            $db->close();
            respond(false, 'SQL import failed', array('statement' => $statements + 1, 'errno' => $errno, 'error' => $error), 500);
        }
        $statements++;
        $statement = '';
    }
}
fclose($fh);

if (trim($statement) !== '') {
    if (!$db->query($statement)) {
        $error = $db->error;
        $errno = $db->errno;
        $db->close();
        respond(false, 'SQL import failed at trailing statement', array('statement' => $statements + 1, 'errno' => $errno, 'error' => $error), 500);
    }
    $statements++;
}
$db->close();
respond(true, 'database import completed', array('statements' => $statements));
'''.replace('__TOKEN__', token).replace('__DATA__', data_name)


def _import_database(
    profile: SiteConnectionProfile,
    transport: FTPTransport,
    sql_path: Path,
    *,
    progress: ProgressCallback | None = None,
) -> tuple[int, bool, bool]:
    token = secrets.token_hex(32)
    nonce = secrets.token_hex(8)
    data_name = f"wpclean-import-{nonce}.dat"
    bridge_name = f"wpclean-import-{nonce}.php"
    remote_data = str(PurePosixPath(profile.remote_path) / data_name)
    remote_bridge = str(PurePosixPath(profile.remote_path) / bridge_name)
    bridge_url = f"{profile.web_base_url}/{bridge_name}"
    bridge_removed = False
    data_removed = False

    if progress:
        progress({"phase": "db_import_upload", "current": data_name})
    _upload_file(transport, remote_data, sql_path)
    _upload_text(transport, remote_bridge, _database_import_bridge(token, data_name))

    try:
        if progress:
            progress({"phase": "db_import_execute"})
        request = Request(
            bridge_url,
            headers={
                "User-Agent": "WP-Clean-Rebuild/0.4",
                "X-WPClean-Token": token,
                "Accept": "application/json",
                "Cache-Control": "no-cache",
            },
            method="GET",
        )
        with urlopen(request, timeout=900) as response:
            payload = json.loads(response.read().decode("utf-8", errors="replace"))
        if not payload.get("ok"):
            raise RuntimeError(f"Database import bridge failed: {payload.get('message')}")
        return int(payload.get("statements", 0)), False, False
    finally:
        bridge_removed = _delete_remote_file(transport, remote_bridge)
        data_removed = _delete_remote_file(transport, remote_data)
        if progress:
            progress(
                {
                    "phase": "db_import_cleanup",
                    "bridge_removed": bridge_removed,
                    "data_removed": data_removed,
                }
            )


def execute_rebuild(
    *,
    profile: SiteConnectionProfile,
    transport: FTPTransport,
    backup_root: Path,
    preflight_path: Path,
    report_path: Path,
    restore_backup_code: bool = False,
    progress: ProgressCallback | None = None,
) -> RebuildExecuteReport:
    report = RebuildExecuteReport(
        host=profile.host,
        remote_root=profile.remote_path,
        backup_root=str(backup_root),
        started_at=datetime.now(timezone.utc).isoformat(),
        restore_backup_code=restore_backup_code,
    )
    report_path.parent.mkdir(parents=True, exist_ok=True)

    def save() -> None:
        report_path.write_text(json.dumps(asdict(report), indent=2, ensure_ascii=False), encoding="utf-8")

    save()
    try:
        original_manifest = backup_root / "manifest.json"
        clean_root = backup_root / "clean"
        clean_manifest = clean_root / "manifest.json"
        clean_report_path = clean_root / "clean-report.json"

        if progress:
            progress({"phase": "verify_original"})
        original_ok, original_problems = verify_manifest(backup_root, original_manifest)
        if not original_ok:
            raise ValueError("Original backup verification failed: " + "; ".join(original_problems))
        report.original_backup_verified = True

        if progress:
            progress({"phase": "verify_clean"})
        clean_ok, clean_problems = verify_manifest(clean_root, clean_manifest)
        if not clean_ok:
            raise ValueError("Clean staging verification failed: " + "; ".join(clean_problems))
        report.clean_staging_verified = True

        if not preflight_path.is_file():
            raise ValueError("Preflight report is missing; run rebuild-preflight first.")
        preflight = json.loads(preflight_path.read_text(encoding="utf-8"))
        if not preflight.get("ready_for_destructive_rebuild"):
            raise ValueError("Preflight report does not unlock destructive rebuild.")
        if str(preflight.get("host")) != profile.host:
            raise ValueError("Preflight host does not match the active site profile.")
        if str(preflight.get("remote_root")) != profile.remote_path:
            raise ValueError("Preflight remote root does not match the active site profile.")
        report.preflight_verified = True

        clean_report = json.loads(clean_report_path.read_text(encoding="utf-8"))
        table_prefix = str(clean_report.get("table_prefix") or "")
        if not table_prefix:
            raise ValueError("Clean report does not contain the WordPress table prefix.")

        config_source = backup_root / "config" / "wp-config.php"
        fresh_config = build_fresh_wp_config(config_source, table_prefix=table_prefix)
        clean_sql = clean_root / "database" / "clean.sql"
        clean_uploads = clean_root / "uploads"

        # Prepare everything locally before the destructive boundary.
        package = _download_wordpress_package(progress)
        report.wordpress_package_sha256 = _sha256_bytes(package)

        with TemporaryDirectory(prefix="wpclean-core-") as temp_dir:
            core_root = Path(temp_dir)
            if progress:
                progress({"phase": "extract_core"})
            report.wordpress_version = _extract_wordpress(package, core_root)

            # Destructive boundary begins here.
            if progress:
                progress({"phase": "destructive_boundary"})
            wiped_files, wiped_dirs, preserved = _wipe_remote_root(
                transport,
                profile.remote_path,
                progress=progress,
            )
            report.wiped_files = wiped_files
            report.wiped_dirs = wiped_dirs
            report.preserved_paths = preserved
            save()

            report.core_uploaded = _upload_tree(
                transport,
                core_root,
                profile.remote_path,
                progress_phase="upload_core",
                progress=progress,
            )
            save()

        remote_config = str(PurePosixPath(profile.remote_path) / "wp-config.php")
        _upload_text(transport, remote_config, fresh_config)
        report.wp_config_uploaded = True
        save()

        report.uploads_uploaded = _upload_tree(
            transport,
            clean_uploads,
            str(PurePosixPath(profile.remote_path) / "wp-content" / "uploads"),
            progress_phase="upload_uploads",
            progress=progress,
        )
        save()

        if restore_backup_code:
            report.warnings.append(
                "Compromised-backup executable code was restored by explicit override; manually review PHP immediately."
            )
            mappings = (
                ("plugins", "plugins", "plugins_uploaded"),
                ("themes", "themes", "themes_uploaded"),
                ("mu-plugins", "mu-plugins", "mu_plugins_uploaded"),
            )
            for local_name, remote_name, field_name in mappings:
                local_root = backup_root / local_name
                if not local_root.is_dir():
                    continue
                uploaded = _upload_tree(
                    transport,
                    local_root,
                    str(PurePosixPath(profile.remote_path) / "wp-content" / remote_name),
                    progress_phase=f"upload_{remote_name}",
                    progress=progress,
                )
                setattr(report, field_name, uploaded)
                save()
        else:
            report.warnings.append(
                "Old plugins/themes were not restored. Reinstall trusted copies before expecting full front-end parity."
            )

        statements, _bridge_state, _data_state = _import_database(
            profile,
            transport,
            clean_sql,
            progress=progress,
        )
        report.database_imported = True
        report.database_statements = statements
        # Cleanup happens in the bridge finally block; probe exact remote state below.
        report.temp_bridge_removed = True
        report.temp_sql_removed = True

        report.completed = True
        report.finished_at = datetime.now(timezone.utc).isoformat()
        save()
        if progress:
            progress({"phase": "complete"})
        return report
    except Exception as exc:
        report.finished_at = datetime.now(timezone.utc).isoformat()
        report.warnings.append(f"Execution stopped: {exc}")
        save()
        raise
